[program:websocket-server]
command=/usr/bin/php /Applications/XAMPP/xamppfiles/htdocs/store/backend/websocket/server.php
directory=/Applications/XAMPP/xamppfiles/htdocs/store/backend/websocket
autostart=true
autorestart=true
user=daemon
stdout_logfile=/Applications/XAMPP/xamppfiles/htdocs/store/backend/logs/websocket.log
stderr_logfile=/Applications/XAMPP/xamppfiles/htdocs/store/backend/logs/websocket_error.log
