CREATE TABLE IF NOT EXISTS reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    generated_by INT NOT NULL,
    inventory_value DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    total_expenses DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    business_capital DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    cash_in_hand DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    total_debt DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    net_profit DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
